Added clearAllData to DAL
Leasehold/ldpos-knex-dal pull request #6
Opened 2021-02-20 18:26 UTC by sacOO7

- Added separate implementation for truncating all tables.
- Refactored code for checking empty tables.
- Refactored tests.

2021-02-20 19:09 UTC, jondubois requested changes

2021-02-20 19:13 UTC, sacOO7 commented on knex/knex-client.js
> +      await this.truncate(tableName);
Okay

2021-02-20 19:13 UTC, sacOO7 commented on src/index.js
> +    console.warn("Clearing data from all tables")
Okay

2021-02-20 20:30 UTC, jondubois approved these changes

2021-02-20 20:30 UTC, merged

2021-02-22 14:08 UTC, sacOO7 commented
Related to #4